@HostAddress = http://localhost:61096

###

POST {{HostAddress}}/nats/publish/
Content-Type: application/json

{
  "subject": "events.mouse.click",
  "name": "Mouse Event",
  "description": "Mouse Event Description",
  "priority": "0.1"
}

###

POST {{HostAddress}}/nats/publish/
Content-Type: application/json

{
  "subject": "events.key.a",
  "name": "Key Event",
  "description": "Key Event Description",
  "priority": "0.5"
}
